### ISSUE TITLE
Crash opening document

### ISSUE THREAD

**Issue by stivoberlin** [xceedsoftware/DocX#177]
this command
 DocX.Load("test.docx")
raise this exception :

System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no matching element
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xceed.Words.NET.Paragraph.GetParagraphNumberProperties()
   at Xceed.Words.NET.Paragraph.get_ParagraphNumberProperties()
   at Xceed.Words.NET.Paragraph.get_IsListItem()
   at Xceed.Words.NET.Container.InitParagraphs(List`1 paragraphs)
   at Xceed.Words.NET.Container.get_Paragraphs()
   at Xceed.Words.NET.DocX.get_Paragraphs()
   at Xceed.Words.NET.DocX.PostLoad(Package& package)
   at Xceed.Words.NET.DocX.Load(String filename)
   

[test.docx](https://github.com/xceedsoftware/DocX/files/1559460/test.docx)

**Comment by XceedBoucherS** [comment]
This is fixed in v1.2.

You can get v1.2 here : https://xceed.com/xceed-words-for-net/

Thanks.

**Comment by STARFOX10** [comment]
Hello ! @XceedBoucherS 
I have the similar issue with the "ConvertToPdf" function

I put all my code in commentary and just leave this to test :

``

System.InvalidOperationException: Sequence contains no matching element.
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xceed.Document.NET.HelperFunctions.GetListItemStartValue(List list, Int32 level)
   at Xceed.Document.NET.PdfListsInfo.AddDictionaryEntry(List list, Int32 itemLevel, Boolean isSubSection)
   at Xceed.Document.NET.PdfListItem.UpdateText(Text text)
   at Xceed.Document.NET.PdfParagraph.FillContent(Text text, Boolean isMeasuring)
   at Xceed.Document.NET.PdfTable.UpdateText(Text text)
   at Xceed.Document.NET.PdfParagraph.CreatePdfTable(Graphics graphics)
   at Xceed.Document.NET.PdfConverter.DrawPdfTable(PdfParagraph paragraph, Single marginTop, Single marginBottom, Int32 paragraphDrawnLines)
   at Xceed.Document.NET.PdfConverter.DrawPdfParagraph(PdfParagraph paragraph, Single marginTop, Single marginBottom, Boolean isHeaderFooter)
   at Xceed.Document.NET.PdfConverter.CreatePdfParagraphs(IEnumerable`1 paragraphs)
   at Xceed.Document.NET.PdfConverter.Convert()
   at Xceed.Document.NET.Document.ConvertToPdf(Document fileToConvert, String outputFileName)
   at TestLisaMVC.UIWeb.Controllers.ModelController.XceedFusionPDF(String resultClientInfos, String choixUtilisateur) in \\Controllers\ModelController.cs:ligne 377
