### ISSUE TITLE
Error while converting a DocX (StringToInt in GetColorFromHtml)

### ISSUE THREAD

**Issue by MarcAndreJean** [xceedsoftware/DocX#274]
I've tried to convert a DocX (generated by DocX v1.5) and this error popped out. It's seem coming from a conversion string to int of a 'html code'. Of course, i'm using color in my Docx.

Tell me if you want my DocX for test, I could send it to you by email (the docx contains confidentiel data of my client and I don't want to publish them publicly). Just give me an email soo I can reach you.

Here part of the log:
`Could not find any recognizable digits.
System.FormatException: Could not find any recognizable digits.
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags)
   at System.Convert.ToInt32(String value, Int32 fromBase)
   at Xceed.Document.NET.HelperFunctions.GetColorFromHtml(String stringColor, String autoColor)
   at Xceed.Document.NET.PdfParagraph.ApplyParagraphBorders(Text text)
   at Xceed.Document.NET.PdfParagraph.CreatePdfText(IList wrappedObjectInfoList, Boolean isMeasuring)
   at Xceed.Document.NET.PdfConverter.DrawPdfParagraph(PdfParagraph paragraph, Single marginTop, Single marginBottom, Boolean isHeaderFooter)
   at Xceed.Document.NET.PdfConverter.CreatePdfParagraphs(IEnumerable1 paragraphs)
   at Xceed.Document.NET.PdfConverter.Convert()
   at Xceed.Document.NET.Document.ConvertToPdf(Document fileToConvert, Stream outputStream)`

**Comment by XceedBoucherS** [comment]
Hi,
You are using a feature of "Xceed Words for .NET", the commercial version of "DocX". 
GitHub only contains the free version : "DocX".
I suggest you ask your question through our support : support@xceed.com
Thank you.
