### ISSUE TITLE
Can't load a .docx that contains a bad hyperlink: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by brianberns** [xceedsoftware/DocX#324]
Attempting to load a Word document that contains an invalid hyperlink causes an error. The attached file demonstrates the problem.

```
System.UriFormatException: Invalid URI: The hostname could not be parsed.

at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection.ProcessRelationshipAttributes(XmlCompatibilityReader reader)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection.ParseRelationshipPart(PackagePart part)
   at MS.Internal.IO.Packaging.InternalRelationshipCollection..ctor(Package package, PackagePart part)
   at System.IO.Packaging.PackagePart.EnsureRelationships()
   at System.IO.Packaging.PackagePart.GetRelationshipsHelper(String filterString)
   at System.IO.Packaging.PackagePart.GetRelationships()
   at Xceed.Words.NET.DocX.PopulateDocument(DocX document, Package package)
   at Xceed.Words.NET.DocX.PostLoad(Package& package)
   at Xceed.Words.NET.DocX.Load(String filename)

```
[Word.docx](https://github.com/xceedsoftware/DocX/files/3192127/Word.docx)

**Comment by XceedBoucherS** [comment]
Hi,
You are right, this is not handled. This error is thrown by the System.IO.Packaging dll which is used by "DocX".
We manage to fix this. The fix will be included in v1.7.

Thank you.
