### ISSUE TITLE
How to add CheckBox to paragraph? Getting an error: Sequence contains no elements

### ISSUE THREAD

**Issue by umbarov** [xceedsoftware/DocX#437]
Hi,
I have some problems with adding a checkbox to a paragraph. How do I add a checkbox to a paragraph correctly? Here is a simple repro code:

```cs
using Xceed.Words.NET;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Licenser.LicenseKey = "license-key-here";
            using (var doc = DocX.Create(""))
            {
                var p = doc.InsertParagraph();
                var checkbox = doc.AddCheckBox(true);
                p.AppendCheckBox(checkbox); // This is line 14

                doc.SaveAs("./new-doc.docx");
            }
        }
    }
}
```
And here is an error:
```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Xceed.Document.NET.Paragraph.AppendCheckBox(CheckBox c)
   at ConsoleApp1.Program.Main(String[] args) in .../Program.cs:line 14

```

**Comment by umbarov** [comment]
I got reply from the Xceed support team. And this is a bug inserting checkbox to an empty paragraph. Fix: Add another component to the paragraph before adding a checkbox.
